server:
  port: 8080

spring:
  datasource:
    username: root
    #    以零开始的密码必须写成字符串模式
    password: root
    url: jdbc:mariadb://127.0.0.1:3309/booksystem
    driver-class-name: org.mariadb.jdbc.Driver
  #    driver-class-name: org.apache.ibatis.datasource.unpooled.UnpooledDataSource.DriverProxy
  application:
    name: books
  web:
    resources:
      static-locations: /static/
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.micaros.books.pojo


#swagger:
#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: springfox swagger 3.0整合Demo
#  try-host: http://localhost:${server.port}

